name: 'Hola Mundo'
description: 'Saludar a alguien y guardar la fecha'
inputs:
  who-to-greet:
    description: 'A quien saludar'
    required: true
    default: 'Mundo'
outputs:
  time:
    description: 'La fecha en que nos conocimos'
runs:
  using: 'docker'
  image: docker://crineth/hello-world-docker-action
  args:
    - ${{ inputs.who-to-greet }}